[package]
name = "bdsm"
version = "0.1.0"
authors = ["bubbyroosh"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rargsxd = "0.1.6"
yaml-rust = "0.4.5"

